#:kivy 1.0.9

<LazySusan>
	canvas.before: 
		Rotate: 
			angle: root.angle
			origin: self.center
		Color: 
			rgba: 1,1,1,0.2
		Ellipse: 
			size: 0.166*root.size[0], 0.166*root.size[0]
			pos: 0.5*root.size[0]-0.166*root.size[0]/2, 0.5*root.size[1]-0.166*root.size[0]/2
	Label:
		id: label_widget
		text: 'widget'
		pos: 0.5*root.size[0], 0.5*root.size[1]
		
<KJMethod>:
	canvas.before:
		Color: 
			rgb: 0,0,0 
		Rectangle: 
			size: root.size
	Menu:
	LazySusan: